# Generated by Django 3.2.3 on 2021-05-30 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('promo', models.CharField(choices=[('L2', 'L2'), ('L3', 'L3'), ('M1GL', 'M1GL'), ('M2GL', 'M2GL'), ('M1RSD', 'M1RSD'), ('M2RSD', 'M2RSD'), ('M1MID', 'M1MID'), ('M2MID', 'M2MID'), ('M1SIC', 'M1SIC'), ('M2SIC', 'M2SIC')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Devoirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('type_dev', models.CharField(choices=[('sommative', 'sommative'), ('formative', 'formative')], max_length=10)),
                ('date_fin', models.DateField()),
                ('date_dep', models.DateField(auto_now=True)),
                ('fichier', models.FileField(upload_to='devoir')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('promo', models.CharField(choices=[('L2', 'L2'), ('L3', 'L3'), ('M1GL', 'M1GL'), ('M2GL', 'M2GL'), ('M1RSD', 'M1RSD'), ('M2RSD', 'M2RSD'), ('M1MID', 'M1MID'), ('M2MID', 'M2MID'), ('M1SIC', 'M1SIC'), ('M2SIC', 'M2SIC')], max_length=6)),
                ('date_naiss', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('date_soumission', models.DateField(auto_now=True)),
                ('solution', models.FileField(upload_to='solutions')),
                ('id_dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoir.devoirs')),
                ('id_etud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoir.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naiss', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='devoirs',
            name='id_ens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoir.enseignants'),
        ),
        migrations.AddField(
            model_name='devoirs',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoir.categorie'),
        ),
    ]
